### PR TITLE
Quick Usage Example in Readme

### PR DESCRIPTION
**Pull request by caseywatts**

### CODE REVIEW

**Comment by caseywatts** [comment]
How do we install telex, since it's private gem?

**Comment by apg** [comment]
@caseywatts you can add our internal, private gem source: [instructions](https://gemgate-heroku-internal-gems.herokuapp.com/setup-instructions).

**Comment by caseywatts** [comment]
sweet! thanks @apg

**Comment by caseywatts** [comment]
updated this PR to say that :)

**Pull request merged**
